### ISSUE TITLE
How to run Eclipse Smart Home Server through Karaf ?

### ISSUE THREAD

**Issue by amarpulli1994** [maggu2810/shk#8] opened 2017-02-03 13:02 UTC
Hello,
I am trying to access ESH server through karaf, but don't know how to run it. When I refereed link https://karaf.apache.org/manual/latest, as per according to link  by using  bin/karaf.bat for windows to run karaf . I also tried bin/karaf.bat command it doesn't worked for me. I downloaded project and then extract it and then clean the project by using "mvn clean install", and then getting the  project successfully build. I don't know how to launch ESH server through karaf.
Thanks,
Amar.

**Comment by maggu2810** [comment] 2017-02-03 16:17
You could check out this repo and call `mvn clean install`.
After that a custom Karaf distribution is created, too. Have a look at `distributions/base/target`. There you will find an archive that contains the custom distribution. You can also look at the assemblies before they are packed in the subdir (of the one above) assemblies, and call `bin/karaf` at this place.

**Comment by amarpulli1994** [comment] 2017-02-04 04:53
Hello,
Thanks for your suggestions. Which tag I have to checkout in repo.
Thanks,
Amar.

**Comment by kirantpatil** [comment] 2017-02-04 04:55
@amarpulli544,

Please mention which branch or tag are you using ?

When you run bin/karaf.bat command what output you are getting on command prompt ?

Any other command output would help author to understand your issue better.

Also include your configuration details like  versions of maven, java and so on.

Thanks.

**Comment by amarpulli1994** [comment] 2017-02-04 05:34
@maggu2810 
I have downloaded master repository and then checkout to master, call mvn clean install. After build success getting the full repository. When I tried to run karaf through command prompt getting the errors see below mentioned

```
D:\Eclipse_SmartHome\shk\distributions\base\target\assembly>bin\karaf.bat
'findstr' is not recognized as an internal or external command,
operable program or batch file.
'findstr' is not recognized as an internal or external command,
operable program or batch file.
        __ __                  ____
       / //_/____ __________ _/ __/
      / ,<  / __ `/ ___/ __ `/ /_
     / /| |/ /_/ / /  / /_/ / __/
    /_/ |_|\__,_/_/   \__,_/_/

  Apache Karaf (4.0.8)

Hit '<tab>' for a list of available commands
and '[cmd] --help' for help on a specific command.
Hit '<ctrl-d>' or type 'system:shutdown' or 'logout' to shutdown Karaf.

karaf@root()> Error:  Could not parse XML contribution for "org.eclipse.emf.ecor
e//plugin.xml". Any contributed extensions and extension points will be ignored.

Error:  Could not parse XML contribution for "org.eclipse.emf.ecore.xmi//plugin.
xml". Any contributed extensions and extension points will be ignored.
Error:  Could not parse XML contribution for "org.eclipse.equinox.registry//plug
in.xml". Any contributed extensions and extension points will be ignored.
Error:  Could not parse XML contribution for "org.eclipse.xtext.xbase//plugin.xm
l". Any contributed extensions and extension points will be ignored.
Error:  Could not parse XML contribution for "org.eclipse.smarthome.model.persis
tence//plugin.xml". Any contributed extensions and extension points will be igno
red.
Error:  Could not parse XML contribution for "org.eclipse.xtext.common.types//pl
ugin.xml". Any contributed extensions and extension points will be ignored.
Error:  Could not parse XML contribution for "org.eclipse.smarthome.model.item//
plugin.xml". Any contributed extensions and extension points will be ignored.
Error:  Could not parse XML contribution for "org.eclipse.xtext//plugin.xml". An
y contributed extensions and extension points will be ignored.
Error:  Could not parse XML contribution for "org.eclipse.smarthome.model.sitema
p//plugin.xml". Any contributed extensions and extension points will be ignored.

Error:  Could not parse XML contribution for "org.eclipse.smarthome.model.script
//plugin.xml". Any contributed extensions and extension points will be ignored.
Error:  Could not parse XML contribution for "org.eclipse.smarthome.model.rule//
plugin.xml". Any contributed extensions and extension points will be ignored.
Error:  Could not parse XML contribution for "org.eclipse.smarthome.model.thing/
/plugin.xml". Any contributed extensions and extension points will be ignored.
```
Thanks ,
Amar.

**Comment by maggu2810** [comment] 2017-02-04 08:45
```text
'findstr' is not recognized as an internal or external command, operable program or batch file.
'findstr' is not recognized as an internal or external command, operable program or batch file.
```
I have never seen this errors, but I must admit I never run Karaf on Windows myself.
IMHO: This messages are not related to this project, but to the upstream Karaf one or to your windows setup (at least I don't modify the karaf.bat).
If you Google this error message there are a lot of hits how to fix that (I can't try it because I have no Windows running).


```
Error:  Could not parse XML contribution for "org.eclipse.emf.ecore//plugin.xml". Any contributed extensions and extension points will be ignored.
Error:  Could not parse XML contribution for "org.eclipse.emf.ecore.xmi//plugin.xml". Any contributed extensions and extension points will be ignored.
Error:  Could not parse XML contribution for "org.eclipse.equinox.registry//plugin.xml". Any contributed extensions and extension points will be ignored.
Error:  Could not parse XML contribution for "org.eclipse.xtext.xbase//plugin.xml". Any contributed extensions and extension points will be ignored.
Error:  Could not parse XML contribution for "org.eclipse.smarthome.model.persistence//plugin.xml". Any contributed extensions and extension points will be ignored.
Error:  Could not parse XML contribution for "org.eclipse.xtext.common.types//plugin.xml". Any contributed extensions and extension points will be ignored.
Error:  Could not parse XML contribution for "org.eclipse.smarthome.model.item//plugin.xml". Any contributed extensions and extension points will be ignored.
Error:  Could not parse XML contribution for "org.eclipse.xtext//plugin.xml". Any contributed extensions and extension points will be ignored.
Error:  Could not parse XML contribution for "org.eclipse.smarthome.model.sitemap//plugin.xml". Any contributed extensions and extension points will be ignored.
Error:  Could not parse XML contribution for "org.eclipse.smarthome.model.script//plugin.xml". Any contributed extensions and extension points will be ignored.
Error:  Could not parse XML contribution for "org.eclipse.smarthome.model.rule//plugin.xml". Any contributed extensions and extension points will be ignored.
Error:  Could not parse XML contribution for "org.eclipse.smarthome.model.thing//plugin.xml". Any contributed extensions and extension points will be ignored.
```

This messages could be ignored.
The messages are logged by some Equinox utility bundles, that are needed for Xtext. If you use the Equinox OSGi framework the errors are not logged. If you use the Apache Felix OSGi framework the errors are shown. But all will be working fine (at least nothing is broken that is caused by this messages).

**Comment by amarpulli1994** [comment] 2017-02-04 09:01
@maggu2810 
  These errors are related to ,while karaf running through windows machine. Does this work for linux machine.
Thanks,
Amar.

**Comment by maggu2810** [comment] 2017-02-04 09:29
So, ara there still some issues open?
@amarpulli544 All okay now?

If you would like to build your custom distribution yourself you can also have a look at: https://github.com/maggu2810/smarthome-packaging-sample-karaf

**Comment by maggu2810** [comment] 2017-02-07 06:48
Please close the issue next time yourself.

**Closed as completed by maggu2810** 2017-02-07 06:48 UTC
